package com.example.realestate

object ItemRepository {
    fun getItemByName(name: String): Item? {
        return items.find { it.name.equals(name, ignoreCase = true) }
    }

    fun getItemByCategory(category: String): List<Item>?{
        return items.filter { it.category.equals(category, ignoreCase = true) }
    }

    val items = listOf(
        Item(
            category = "Fruits",
            name = "Apples",
            imageResId = R.drawable.apples,
            unit = "/1kg",
            priceLow = "RM5.70",
            priceHigh = "RM6.30",
            jayaPrice = "RM5.70",
            vgPrice = "RM6.00",
            lotusPrice = "RM5.90",
            bigPrice = "RM6.20",
            aeonPrice = "RM6.30"
        ),
        Item(
            category = "Fruits",
            name = "Mangoes",
            imageResId = R.drawable.mangoes,
            unit = "/1kg",
            priceLow = "RM6.00",
            priceHigh = "RM7.50",
            jayaPrice = "RM6.00",
            vgPrice = "RM7.50",
            lotusPrice = "RM6.20",
            bigPrice = "RM6.80",
            aeonPrice = "RM7.20"
        ),
        Item(
            category = "Fruits",
            name = "Watermelon",
            imageResId = R.drawable.watermelon,
            unit = "/1kg",
            priceLow = "RM2.20",
            priceHigh = "RM3.20",
            jayaPrice = "RM2.50",
            vgPrice = "RM3.00",
            lotusPrice = "RM2.20",
            bigPrice = "RM2.80",
            aeonPrice = "RM3.20"
        ),
        Item(
            category = "Fruits",
            name = "Strawberry",
            imageResId = R.drawable.strawberry,
            unit = "/250g",
            priceLow = "RM9.50",
            priceHigh = "RM11.50",
            jayaPrice = "RM9.50",
            vgPrice = "RM10.50",
            lotusPrice = "RM9.80",
            bigPrice = "RM10.90",
            aeonPrice = "RM11.50"
        ),
        Item(
            category = "Fruits",
            name = "Bananas",
            imageResId = R.drawable.bananas,
            unit = "/1kg",
            priceLow = "RM3.20",
            priceHigh = "RM4.20",
            jayaPrice = "RM3.20",
            vgPrice = "RM4.00",
            lotusPrice = "RM3.50",
            bigPrice = "RM3.80",
            aeonPrice = "RM4.20"
        ),
        Item(
            category = "Fruits",
            name = "Kiwi",
            imageResId = R.drawable.kiwi,
            unit = "/500g",
            priceLow = "RM15.00",
            priceHigh = "RM20.00",
            jayaPrice = "RM17.00",
            vgPrice = "RM18.00",
            lotusPrice = "RM15.00",
            bigPrice = "RM19.00",
            aeonPrice = "RM20.00"
        ),
        Item(
            category = "Fruits",
            name = "Durian (Musang King)",
            imageResId = R.drawable.durian,
            unit = "/1kg",
            priceLow = "RM80.00",
            priceHigh = "RM120.00",
            jayaPrice = "RM90.00",
            vgPrice = "RM100.00",
            lotusPrice = "RM80.00",
            bigPrice = "RM110.00",
            aeonPrice = "RM120.00"
        ),
        Item(
            category = "Fruits",
            name = "Grapes (Red Seedless)",
            imageResId = R.drawable.grapes_red,
            unit = "/500g",
            priceLow = "RM10.00",
            priceHigh = "RM15.00",
            jayaPrice = "RM12.00",
            vgPrice = "RM13.00",
            lotusPrice = "RM10.00",
            bigPrice = "RM14.00",
            aeonPrice = "RM15.00"
        ),
        Item(
            category = "Veggies",
            name = "Ginger",
            imageResId = R.drawable.ginger, // Replace with your image resource
            unit = "/100g",
            priceLow = "RM1.50",
            priceHigh = "RM2.50",
            jayaPrice = "RM1.80",
            vgPrice = "RM2.00",
            lotusPrice = "RM1.50",
            bigPrice = "RM2.20",
            aeonPrice = "RM2.50"
        ),
        Item(
            category = "Veggies",
            name = "Spinach",
            imageResId = R.drawable.spinach, // Replace with your image resource
            unit = "/200g",
            priceLow = "RM2.00",
            priceHigh = "RM3.50",
            jayaPrice = "RM2.50",
            vgPrice = "RM3.00",
            lotusPrice = "RM2.00",
            bigPrice = "RM3.50",
            aeonPrice = "RM2.80"
        ),
        Item(
            category = "Vegetables",
            name = "Tomato",
            imageResId = R.drawable.tomato,
            unit = "/500g",
            priceLow = "RM3.00",
            priceHigh = "RM5.00",
            jayaPrice = "RM3.50",
            vgPrice = "RM4.00",
            lotusPrice = "RM3.00",
            bigPrice = "RM4.50",
            aeonPrice = "RM5.00"
        ),
        Item(
            category = "Vegetables",
            name = "Potato",
            imageResId = R.drawable.potato,
            unit = "/1kg",
            priceLow = "RM3.00",
            priceHigh = "RM5.00",
            jayaPrice = "RM3.50",
            vgPrice = "RM4.00",
            lotusPrice = "RM3.00",
            bigPrice = "RM4.50",
            aeonPrice = "RM5.00"
        ),
        Item(
            category = "Veggies",
            name = "Broccoli",
            imageResId = R.drawable.broccoli, // Replace with your image resource
            unit = "/500g",
            priceLow = "RM4.00",
            priceHigh = "RM6.00",
            jayaPrice = "RM4.50",
            vgPrice = "RM5.00",
            lotusPrice = "RM4.00",
            bigPrice = "RM5.50",
            aeonPrice = "RM6.00"
        ),
        Item(
            category = "Veggies",
            name = "Carrots",
            imageResId = R.drawable.carrots, // Replace with your image resource
            unit = "/500g",
            priceLow = "RM2.50",
            priceHigh = "RM3.50",
            jayaPrice = "RM3.00",
            vgPrice = "RM3.20",
            lotusPrice = "RM2.50",
            bigPrice = "RM3.50",
            aeonPrice = "RM3.00"
        ),
        Item(
        category = "Veggies",
        name = "Cabbage",
        imageResId = R.drawable.cabbage,
        unit = "/500g",
        priceLow = "RM1.50",
        priceHigh = "RM2.50",
        jayaPrice = "RM1.80",
        vgPrice = "RM2.00",
        lotusPrice = "RM1.50",
        bigPrice = "RM2.20",
        aeonPrice = "RM2.50"
        ),
        Item(
        category = "Veggies",
        name = "Lettuce",
        imageResId = R.drawable.lettuce,
        unit = "/1 head",
        priceLow = "RM2.00",
        priceHigh = "RM3.50",
        jayaPrice = "RM2.50",
        vgPrice = "RM3.00",
        lotusPrice = "RM2.00",
        bigPrice = "RM3.50",
        aeonPrice = "RM2.80"
        ),
        Item(
            category = "Meats",
            name = "Chicken Wings",
            imageResId = R.drawable.chicken_wing,
            unit = "/500g",
            priceLow = "RM8.00",
            priceHigh = "RM12.00",
            jayaPrice = "RM9.00",
            vgPrice = "RM10.00",
            lotusPrice = "RM8.00",
            bigPrice = "RM11.00",
            aeonPrice = "RM12.00"
        ),
        Item(
            category = "Meats",
            name = "Beef Steak",
            imageResId = R.drawable.beef_steak,
            unit = "/500g",
            priceLow = "RM30.00",
            priceHigh = "RM40.00",
            jayaPrice = "RM35.00",
            vgPrice = "RM38.00",
            lotusPrice = "RM30.00",
            bigPrice = "RM37.00",
            aeonPrice = "RM40.00"
        ),
        Item(
            category = "Meat",
            name = "Chicken Breast",
            imageResId = R.drawable.chicken_breast,
            unit = "/500g",
            priceLow = "RM10.00",
            priceHigh = "RM12.00",
            jayaPrice = "RM10.50",
            vgPrice = "RM11.00",
            lotusPrice = "RM10.00",
            bigPrice = "RM11.50",
            aeonPrice = "RM12.00"
        ),
        Item(
            category = "Meat",
            name = "Pork Belly",
            imageResId = R.drawable.pork_belly,
            unit = "/500g",
            priceLow = "RM15.00",
            priceHigh = "RM18.00",
            jayaPrice = "RM16.00",
            vgPrice = "RM17.00",
            lotusPrice = "RM15.00",
            bigPrice = "RM17.50",
            aeonPrice = "RM18.00"
        ),
        Item(
            category = "Meat",
            name = "Beef Mince",
            imageResId = R.drawable.beef_mince,
            unit = "/500g",
            priceLow = "RM20.00",
            priceHigh = "RM25.00",
            jayaPrice = "RM22.00",
            vgPrice = "RM23.00",
            lotusPrice = "RM20.00",
            bigPrice = "RM24.00",
            aeonPrice = "RM25.00"
        ),
        Item(
            category = "Meat",
            name = "Lamb Chops",
            imageResId = R.drawable.lamb_chops,
            unit = "/500g",
            priceLow = "RM30.00",
            priceHigh = "RM35.00",
            jayaPrice = "RM32.00",
            vgPrice = "RM33.00",
            lotusPrice = "RM30.00",
            bigPrice = "RM34.00",
            aeonPrice = "RM35.00"
        ),
        Item(
            category = "Fish",
            name = "Salmon",
            imageResId = R.drawable.salmon,
            unit = "/500g",
            priceLow = "RM30.00",
            priceHigh = "RM35.00",
            jayaPrice = "RM32.00",
            vgPrice = "RM33.00",
            lotusPrice = "RM30.00",
            bigPrice = "RM34.00",
            aeonPrice = "RM35.00"
        ),
        Item(
            category = "Fish",
            name = "Tilapia",
            imageResId = R.drawable.tilapia,
            unit = "/500g",
            priceLow = "RM10.00",
            priceHigh = "RM15.00",
            jayaPrice = "RM12.00",
            vgPrice = "RM13.00",
            lotusPrice = "RM10.00",
            bigPrice = "RM14.00",
            aeonPrice = "RM15.00"
        ),
        Item(
            category = "Fish",
            name = "Cod Fillet",
            imageResId = R.drawable.cod_fillet,
            unit = "/500g",
            priceLow = "RM25.00",
            priceHigh = "RM30.00",
            jayaPrice = "RM27.00",
            vgPrice = "RM28.00",
            lotusPrice = "RM25.00",
            bigPrice = "RM29.00",
            aeonPrice = "RM30.00"
        ),
        Item(
            category = "Seafood",
            name = "Prawn",
            imageResId = R.drawable.prawn,
            unit = "/500g",
            priceLow = "RM20.00",
            priceHigh = "RM30.00",
            jayaPrice = "RM25.00",
            vgPrice = "RM28.00",
            lotusPrice = "RM20.00",
            bigPrice = "RM27.00",
            aeonPrice = "RM30.00"
        ),
        Item(
            category = "Seafood",
            name = "Crab",
            imageResId = R.drawable.crab,
            unit = "/kg",
            priceLow = "RM50.00",
            priceHigh = "RM80.00",
            jayaPrice = "RM60.00",
            vgPrice = "RM70.00",
            lotusPrice = "RM50.00",
            bigPrice = "RM65.00",
            aeonPrice = "RM80.00"
        ),
        Item(
            category = "Seafood",
            name = "Squid",
            imageResId = R.drawable.squid,
            unit = "/500g",
            priceLow = "RM15.00",
            priceHigh = "RM20.00",
            jayaPrice = "RM17.00",
            vgPrice = "RM18.00",
            lotusPrice = "RM15.00",
            bigPrice = "RM19.00",
            aeonPrice = "RM20.00"
        ),
        Item(
            category = "Seafood",
            name = "Mussel",
            imageResId = R.drawable.mussel,
            unit = "/500g",
            priceLow = "RM10.00",
            priceHigh = "RM15.00",
            jayaPrice = "RM12.00",
            vgPrice = "RM13.00",
            lotusPrice = "RM10.00",
            bigPrice = "RM14.00",
            aeonPrice = "RM15.00"
        ),
        Item(
            category = "Eggs & Dairy",
            name = "Henry Jones (Organic Milk)",
            imageResId = R.drawable.organic_milk,
            unit = "1L",
            priceLow = "RM10.00",
            priceHigh = "RM15.00",
            jayaPrice = "RM12.00",
            vgPrice = "RM13.00",
            lotusPrice = "RM10.00",
            bigPrice = "RM14.00",
            aeonPrice = "RM15.00"
        ),
        Item(
            category = "Eggs & Dairy",
            name = "Farm Fresh (Fresh Milk)",
            imageResId = R.drawable.fresh_milk,
            unit = "1L",
            priceLow = "RM6.00",
            priceHigh = "RM8.00",
            jayaPrice = "RM6.50",
            vgPrice = "RM7.00",
            lotusPrice = "RM6.00",
            bigPrice = "RM7.50",
            aeonPrice = "RM8.00"
        ),
        Item(
            category = "Eggs & Dairy",
            name = "Chicken Eggs (Grade A)",
            imageResId = R.drawable.eggs,
            unit = "10's",
            priceLow = "RM6.00",
            priceHigh = "RM8.00",
            jayaPrice = "RM7.00",
            vgPrice = "RM7.50",
            lotusPrice = "RM6.00",
            bigPrice = "RM7.80",
            aeonPrice = "RM8.00"
        ),
        Item(
            category = "Eggs & Dairy",
            name = "Yogurt (Plain)",
            imageResId = R.drawable.yogurt_plain,
            unit = "150g",
            priceLow = "RM2.00",
            priceHigh = "RM3.00",
            jayaPrice = "RM2.50",
            vgPrice = "RM2.80",
            lotusPrice = "RM2.00",
            bigPrice = "RM2.70",
            aeonPrice = "RM3.00"
        ),
        Item(
            category = "Eggs & Dairy",
            name = "Emborg Cream Cheese",
            imageResId = R.drawable.emborg_cream_cheese,
            unit = "200g",
            priceLow = "RM15.00",
            priceHigh = "RM20.00",
            jayaPrice = "RM17.00",
            vgPrice = "RM18.00",
            lotusPrice = "RM15.00",
            bigPrice = "RM19.00",
            aeonPrice = "RM20.00"
        ),
        Item(
            category = "Eggs & Dairy",
            name = "Emborg Cheddar Cheese",
            imageResId = R.drawable.emborg_cheddar_cheese,
            unit = "200g",
            priceLow = "RM18.00",
            priceHigh = "RM25.00",
            jayaPrice = "RM20.00",
            vgPrice = "RM22.00",
            lotusPrice = "RM18.00",
            bigPrice = "RM23.00",
            aeonPrice = "RM25.00"
        ),
        Item(
            category = "Snacks",
            name = "Buldak Ramyeon",
            imageResId = R.drawable.buldak_ramen,
            unit = "1 pack",
            priceLow = "RM5.00",
            priceHigh = "RM7.00",
            jayaPrice = "RM6.00",
            vgPrice = "RM6.50",
            lotusPrice = "RM5.00",
            bigPrice = "RM6.80",
            aeonPrice = "RM7.00"
        ),
        Item(
            category = "Snacks",
            name = "Indomie Mi Goreng",
            imageResId = R.drawable.indomie,
            unit = "1 pack",
            priceLow = "RM2.00",
            priceHigh = "RM3.00",
            jayaPrice = "RM2.50",
            vgPrice = "RM2.80",
            lotusPrice = "RM2.00",
            bigPrice = "RM2.70",
            aeonPrice = "RM3.00"
        ),
        Item(
            category = "Snacks",
            name = "Maggi Mac & Cheese",
            imageResId = R.drawable.mac_n_cheese,
            unit = "1 pack",
            priceLow = "RM2.50",
            priceHigh = "RM3.50",
            jayaPrice = "RM3.00",
            vgPrice = "RM3.30",
            lotusPrice = "RM2.50",
            bigPrice = "RM3.20",
            aeonPrice = "RM3.50"
        ),
        Item(
            category = "Snacks",
            name = "Mamee Instant Noodle (Kari)",
            imageResId = R.drawable.mamee,
            unit = "1 pack",
            priceLow = "RM2.00",
            priceHigh = "RM3.00",
            jayaPrice = "RM2.50",
            vgPrice = "RM2.80",
            lotusPrice = "RM2.00",
            bigPrice = "RM2.70",
            aeonPrice = "RM3.00"
        ),
        Item(
            category = "Snacks",
            name = "Oreo Cookies",
            imageResId = R.drawable.oreo,
            unit = "1 packet",
            priceLow = "RM4.00",
            priceHigh = "RM6.00",
            jayaPrice = "RM4.50",
            vgPrice = "RM5.00",
            lotusPrice = "RM4.00",
            bigPrice = "RM5.50",
            aeonPrice = "RM6.00"
        ),
        Item(
            category = "Snacks",
            name = "Kinder Bueno",
            imageResId = R.drawable.kinder_bueno,
            unit = "1 pack",
            priceLow = "RM5.00",
            priceHigh = "RM7.00",
            jayaPrice = "RM6.00",
            vgPrice = "RM6.50",
            lotusPrice = "RM5.00",
            bigPrice = "RM6.80",
            aeonPrice = "RM7.00"
        ),
        Item(
            category = "Snacks",
            name = "Doritos Tortilla Chips",
            imageResId = R.drawable.doritos,
            unit = "1 packet",
            priceLow = "RM3.00",
            priceHigh = "RM4.00",
            jayaPrice = "RM3.50",
            vgPrice = "RM3.80",
            lotusPrice = "RM3.00",
            bigPrice = "RM3.70",
            aeonPrice = "RM4.00"
        ),
        Item(
            category = "Snacks",
            name = "Lays Potato Chips (Spicy)",
            imageResId = R.drawable.lays,
            unit = "1 packet",
            priceLow = "RM2.00",
            priceHigh = "RM3.00",
            jayaPrice = "RM2.50",
            vgPrice = "RM2.80",
            lotusPrice = "RM2.00",
            bigPrice = "RM2.70",
            aeonPrice = "RM3.00"
        )
    )

}